### PR TITLE
Fixing drhod_dz approximation in Shipway and Hill

### PR DESCRIPTION
**Pull request by sajjadazimi**
returning drhod_dz instead of drho_dz for solving for rhod in settings constructor

### CODE REVIEW

**Comment by slayoo** [comment]
Thank you, @sajjadazimi!

**Comment by slayoo** [comment]
BTW, would be great to compare at some point how the results match the "bin-microphysics" example in PyMPDATA which uses the same setup: https://github.com/atmos-cloud-sim-uj/PyMPDATA-examples/blob/main/PyMPDATA_examples/Shipway_and_Hill_2012/settings.py

**Comment by sajjadazimi** [comment]
Using the actual drhod_dz instead of the approximate drho_dz for finding rhod profile changes a bit the resulting rhod profile and consequently T and p profiles (by a tiny fraction but still important specially for calibration of microphysics parameters in bulk schemes). Maybe we could apply the same change in PyMPDATA too?

**Comment by slayoo** [comment]
CC @edejong-caltech
Emily, merging this in will alter the single-column kinematic results as it redefines (corrects) the density profile.
Please confirm if you're OK with this change.

**Pull request merged**
