### PR TITLE
save spectrum and attributes / automatic adjustment of the reservoir …

### PR DESCRIPTION
**Pull request by sajjadazimi**
…depth wrt updraft / minor updates

### CODE REVIEW

**Comment by slayoo** [comment]
@sajjadazimi Pylint still complains :)
```
************* Module PySDM_examples.Shipway_and_Hill_2012.simulation
PySDM_examples/Shipway_and_Hill_2012/simulation.py:168:8: C0206: Consider iterating with .items() (consider-using-dict-items)
```

**Comment by slayoo** [comment]
We have also still the .DS_store files here (see the "Files changed" tab above):
Screenshot from 2022-05-16 13-45-44


And of course, first of all, big thanks for the updates to this PR and for addressing all these points!

**Comment by slayoo** [comment]
Let also suggest renaming `particles_per_cm3` to `particles_per_cm3_STP` as given the density gradient we interpret this concentration as for standard temperature and pressure (dry air)

**Comment by slayoo** [comment]
Also, let's switch from conveying the physical unit in the parameter name, so:
``particles_per_volume_STP = 50 / si.cm**3`` instead of ``particles_per_cm3 = 50``

**Comment by slayoo** [comment]
We also need to open a corresponding PR to PySDM itself as the changes here break Shipway_and_Hill smoke tests:
- https://github.com/atmos-cloud-sim-uj/PySDM/blob/1b5966f84b8464912f8d69ff2cb969aec8d9a31b/tests/smoke_tests/shipway_and_hill_2012/test_initial_condition.py#L29
- https://github.com/atmos-cloud-sim-uj/PySDM/blob/70cdc836218b3530d26509e952875a9c2ddca8a3/tests/smoke_tests/shipway_and_hill_2012/test_few_steps.py#L27

**Comment by slayoo** [comment]
I'd also suggest we make the new saving logic not executed by default for the existing Jupyter notebooks as it makes them run forever, and for no reason - the save spectra are not plotted

**Comment by sajjadazimi** [comment]
> I'd also suggest we make the new saving logic not executed by default for the existing Jupyter notebooks as it makes them run forever, and for no reason - the save spectra are not plotted

We can remove the items in settings.save_spec_and_attr_times. That will do the job.

**Comment by sajjadazimi** [comment]
> We also need to open a corresponding PR to PySDM itself as the changes here break Shipway_and_Hill smoke tests:
> 
> * https://github.com/atmos-cloud-sim-uj/PySDM/blob/1b5966f84b8464912f8d69ff2cb969aec8d9a31b/tests/smoke_tests/shipway_and_hill_2012/test_initial_condition.py#L29
> * https://github.com/atmos-cloud-sim-uj/PySDM/blob/70cdc836218b3530d26509e952875a9c2ddca8a3/tests/smoke_tests/shipway_and_hill_2012/test_few_steps.py#L27

I'll create a PR now

**Pull request merged**
