### PR TITLE
update Lowe example

### PR DESCRIPTION
**Pull request by claresinger**
- [x] Update aerosol.py to include needed generality for fig 3
- [x] Update settings.py to use all new PySDM features like latent heats and take input as `dz` not `dt`
- [x] Update simulation.py to inherit from BasicSimulation
- [x] Update fig 1 and fig 2 accordingly
- [x] Update fig2b to include activated fraction definition of CDNC
- [x] Update fig2c to have correct units

### CODE REVIEW

**Comment by claresinger** [comment]
[fig_2c.pdf](https://github.com/atmos-cloud-sim-uj/PySDM-examples/files/8075911/fig_2c.pdf)
Fig 2c units still have issue. Values are off by 10x.

**Comment by slayoo** [comment]
closing and opening to trigger rerun after fixing the MarkupSafe problem (#129)

**Comment by slayoo** [comment]
green! @claresinger, OK to merge?

**Comment by claresinger** [comment]
> green! @claresinger, OK to merge?

I don't think so... Fig 2c still is wrong.
[fig_2c.pdf](https://github.com/atmos-cloud-sim-uj/PySDM-examples/files/8120788/fig_2c.pdf)

**Comment by slayoo** [comment]
Shall we merge this one and summarise the remaining TODOs in https://github.com/atmos-cloud-sim-uj/PySDM/issues/604 ?

**Comment by slayoo** [comment]
BTW, seems that this time Pylint found a true bug :)
```
PySDM_examples/Lowe_et_al_2019/fig_1.ipynb:cell_6:3:95: W0631: Using possibly undefined loop variable 'label' (undefined-loop-variable)
PySDM_examples/Lowe_et_al_2019/fig_1.ipynb:cell_6:3:95: W0631: Using possibly undefined loop variable 'label' (undefined-loop-variable)
```

**Comment by claresinger** [comment]
@slayoo I updated https://github.com/atmos-cloud-sim-uj/PySDM/issues/604
Assuming all checks pass now, we can merge this.

**Pull request merged**
