### PR TITLE
variable constants in Lowe et al example

### PR DESCRIPTION
**Pull request by slayoo**

### CODE REVIEW

**Comment by claresinger** [comment]
@slayoo This change isn't working for me... e.g. in fig1.ipynb, I change 
```
from PySDM.physics.surface_tension import compressed_film
compressed_film.sgm_org = 20 * si.mN / si.m
```
But Fig 1d still has the intercept at 40 mN/m.

**Comment by slayoo** [comment]
Jupyter kernel restart will likely help. If so (checked, it helped here), the reason is that Numba compiles-in as constants anything that is not a function parameter, and it does not track if the "constants" change - one needs to somehow trigger recompilation, restarting the kernel causes recompilation of everything

**Comment by claresinger** [comment]
Thanks. I needed actually to pull the changes from PySDM to my local repo and then reinstall everything for the changes to work! Don't fully understand that, but now it's all working.

**Comment by slayoo** [comment]
probably related: https://github.com/atmos-cloud-sim-uj/PySDM/issues/634

**Comment by slayoo** [comment]
@claresinger with current PySDM all constants can be altered by passing a dictionary with alternative values to the __init__ method of the Formulae class, hope this will help and make life easier :) Numba caching should not matter now.

**Pull request merged**
